import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["src/tests/**/*.test.ts"],
    exclude: [
      "node_modules/**",
      "dist/**",
      ".storage/**",

      // Existing placeholder files with no suites will be fixed incrementally.
      "src/tests/answerProvenance.test.ts",
      "src/tests/apiContracts.test.ts",
      "src/tests/authMiddleware.test.ts",
      "src/tests/authProtection.test.ts",
      "src/tests/changedFileDetection.test.ts",
      "src/tests/confidenceMetadataIntegration.test.ts",
      "src/tests/confidenceScorer.test.ts",
      "src/tests/contextAssembly.test.ts",
      "src/tests/contextBudget.test.ts",
      "src/tests/debugReport.test.ts",
      "src/tests/fileSnapshotStore.test.ts",
      "src/tests/graphTraversalWeighting.test.ts",
      "src/tests/incrementalGraphUpdate.test.ts",
      "src/tests/incrementalSymbolRefresh.test.ts",
      "src/tests/indexCleanup.test.ts",
      "src/tests/indexedRepositoriesResponseContract.test.ts",
      "src/tests/indexingExecutor.test.ts",
      "src/tests/indexingOperationRetry.test.ts",
      "src/tests/indexingPlan.test.ts",
      "src/tests/indexingRegistryContract.test.ts",
      "src/tests/indexingService.test.ts",
      "src/tests/jwt.test.ts",
      "src/tests/removedFileSymbolPruning.test.ts",
      "src/tests/repositoryArchitectureSummary.test.ts",
      "src/tests/repositoryCleanup.test.ts",
      "src/tests/repositoryCoverage.test.ts",
      "src/tests/repositoryGraph.test.ts",
      "src/tests/repositoryHealthSummary.test.ts",
      "src/tests/repositoryHealthText.test.ts",
      "src/tests/repositoryIsolationRoutes.test.ts",
      "src/tests/repositoryListingIsolation.test.ts",
      "src/tests/repositoryMetadataContract.test.ts",
      "src/tests/repositoryMetadataContractShape.test.ts",
      "src/tests/repositoryOverview.test.ts",
      "src/tests/repositoryOverviewText.test.ts",
      "src/tests/repositoryOwnership.test.ts",
      "src/tests/repositoryOwnershipRoutes.test.ts",
      "src/tests/repositoryStructureSummary.test.ts",
      "src/tests/reranker.test.ts",
      "src/tests/retrievalBlindSpots.test.ts",
      "src/tests/retrievalContextSummary.test.ts",
      "src/tests/retrievalContextText.test.ts",
      "src/tests/retrievalDiversity.test.ts",
      "src/tests/retrievalExplainability.test.ts",
      "src/tests/retrievalExplanation.test.ts",
      "src/tests/retrievalHotspots.test.ts",
      "src/tests/retrievalMetadataExposure.test.ts",
      "src/tests/retrievalQualityScore.test.ts",
      "src/tests/retrievalTrace.test.ts",
      "src/tests/retrySafeIndexing.test.ts",
      "src/tests/sessionOwnership.test.ts",
      "src/tests/sessionRepositoryConsistency.test.ts",
      "src/tests/sessionRepositoryOwnership.test.ts",
      "src/tests/staleDetection.test.ts",
      "src/tests/symbolExtractor.test.ts",
      "src/tests/symbolIndexStore.test.ts",
      "src/tests/symbolIndexStorePersistence.test.ts",
    ],
  },
});